spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/test?allowMultiQueries=true
    username: root
    password: 123456
    schema: classpath:db/schema.sql
    initialization-mode: always

