spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:Test;DB_CLOSE_DELAY=-1;MODE=MySQL
    username: sa
    password:
    schema: classpath:db/schema.sql
    initialization-mode: always